name: Publish
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Build Scully
        uses: cmgriffing/scully-gh-pages-action@v7
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: master

      - name: Set new Git Tag
        uses: azu/action-package-version-to-git-tag@v1
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
